# General Settings
name: Mario Codes
job_title: Java Developer
email: mariocodes1993@gmail.com
description: I work with great passion as a backend developer, currently at Team Neusta. In my free time I enjoy building little personal projects, learning languages or getting lost in nature.
avatar: https://mariocodes.github.io/assets/images/avatar.jpg
favicon: /favicon.ico # TODO
twitter_handler:
analytics_code: # UA-XXXXXXX-2
disqus: # your_disqus_site

# Custom added by me
home_sidebar: Home # String to show as "Home" at the sidebar. It was hardcoded.

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'http://www.linkedin.com/in/MarioCodes' }
-  { name: skype, url: '' }
-  { name: github, url: 'http://www.github.com/MarioCodes' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 0
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "false"

# Serhttps://mariocodes.github.io "https://mariocodes.github.io"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
